name: PR Checks
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]

permissions:
  contents: read
  actions: write

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew build

  gradle_publish:
    runs-on: ubuntu-latest
    needs: gradle-build
    env:
      MY_ENV_VAR: ${{ secrets.MY_SECRET }}
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      PUBLIC_PUBLISH_SIGNING_KEY: ${{ secrets.PUBLIC_PUBLISH_SIGNING_KEY }}
      PUBLIC_PUBLISH_SIGNING_PASSWORD: ${{ secrets.PUBLIC_PUBLISH_SIGNING_PASSWORD }}

    container:
      image: ubuntu:22.04

    steps:
      - name: Install Java 17
        run: |
          apt-get update && apt-get install -y openjdk-17-jdk
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gradle Publish
        run: ./gradlew --build-cache publishToSonatype closeAndReleaseSonatypeStagingRepository
